spring:
  application:
    name: joint-purchase
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5433/joint-purchase
    username: postgres
    password: postgres
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
server:
  port: 8081

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /docs/swagger-ui

grpc:
  client:
    auth:
      address: localhost:9098
      negotiation-type: plaintext
