spring:
  application:
    name: joint-purchase
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5433/joint-purchase
    username: postgres
    password: postgres
